version: "3.8"

services:
  backend:
    env_file:
      - .env
    build:
      context: ./wizybot-api
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./wizybot-frontend
    ports:
      - "80:80" # Escucha tráfico HTTP estándar
      - "443:443" # Escucha tráfico HTTPS seguro
    volumes:
      - ./certs:/etc/nginx/ssl:ro # Inyecta los certificados que creaste en el EC2
    depends_on:
      - backend
