version: "3.8"

services:
  backend:
    env_file:
      - .env
    build:
      context: ./wizybot-api
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./wizybot-frontend
    ports:
      - "3010:80" # Puerto HTTP estándar
    depends_on:
      - backend
